name: s2v2
channels:
  - conda-forge
  - defaults
dependencies:
  - accelerate=0.28.0
  - arviz=0.17.1
  - cairo=1.18.0
  - clang=16.0.6
  - emcee=3.1.4
  - gmp=6.3.0
  - gmpy2=2.1.2
  - huggingface_hub=0.21.4
  - libtorch=2.1.2
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.1
  - pillow=10.2.0
  - pip=24.0
  - pymc=5.11.0
  - pymc-base=5.11.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytensor=2.18.6
  - pytensor-base=2.18.6
  - python=3.11.8
  - pytorch=2.1.2
  - scipy=1.12.0
  - seaborn=0.12.2
  - sympy=1.12
  - tornado=6.3.3
  - tqdm=4.66.2
  - yaml=0.2.5
